name: Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node_version: [18, 20]
   steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "${{ matrix.node_version }}"
    - run: yarn --ignore-scripts --pure-lockfile
    - run: yarn test